# Exclude files
exclude: [Makefile]
excerpt_separator: ""

# Install gems
gems:
  - jekyll-last-modified-at



# Permalinks
permalink: '/:categories/:title/'



# Webpage
timezone: 'Europe/Berlin'
title: 'Statusside'
baseurl: '/flaski-status/'
assets: 'assets/'
mailchimp:
   css: 'https://cdn-images.mailchimp.com/embedcode/classic-ID.css'
   url: 'https://NAME.DC.list-manage.com/subscribe/post?u=U&amp;id=ID'
   csrf: 'CSRF'



# Services
services:
   HOMEPAGE:
      en: Homepage
   API:
      en: API
   REST:
      en: REST API
   DOCS:
      en: Documentation
